import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
const ROOT=path.resolve('.'), PUBLIC=path.join(ROOT,'public'), DB=path.join(ROOT,'data/db.json');
const PORT=Number(process.env.PORT||8080), HOST=process.env.HOST||'127.0.0.1';

const json=async()=>JSON.parse(await fs.readFile(DB,'utf8'));const save=async d=>{let t=DB+'.tmp';await fs.writeFile(t,JSON.stringify(d,null,2));await fs.rename(t,DB)};
const seed=async()=>{let d=await json();if(!d.listings.length){d.listings=[{id:id(),hostId:'seed',title:'Casa moderna con piscina',city:'Ciudad del Este',category:'Casa',price:350000,guests:6,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',description:'Casa cómoda para familias y grupos.',rating:4.9,status:'active',createdAt:new Date().toISOString()},{id:id(),hostId:'seed',title:'Habitación privada acogedora',city:'Presidente Franco',category:'Habitación',price:120000,guests:2,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=80',description:'Habitación para viajeros.',rating:4.9,status:'active',createdAt:new Date().toISOString()},{id:id(),hostId:'seed',title:'Quinta familiar para descansar',city:'Hernandarias',category:'Quinta',price:550000,guests:10,image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=80',description:'Espacio amplio para grupos.',rating:4.7,status:'active',createdAt:new Date().toISOString()},{id:id(),hostId:'seed',title:'Departamento premium',city:'Asunción',category:'Departamento',price:390000,guests:4,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80',description:'Departamento urbano.',rating:4.8,status:'active',createdAt:new Date().toISOString()}];await save(d)}};
const id=()=>crypto.randomUUID();const hash=p=>crypto.scryptSync(p,'RentPy-v1',64).toString('hex');
await seed();
const send=(res,status,data,type='application/json')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; img-src 'self' https: data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'"});res.end(type==='application/json'?JSON.stringify(data):data)};
const body=async req=>{let b='';for await(const c of req)b+=c;if(b.length>1e6)throw Error('payload too large');return b?JSON.parse(b):{}};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let [k,...v]=x.trim().split('=');return [k,decodeURIComponent(v.join('='))]}));
async function user(req){let s=cookies(req).rp_session;if(!s)return null;let d=await json(),x=d.sessions.find(a=>a.token===s&&a.expires>Date.now());return x?d.users.find(u=>u.id===x.userId)||null:null}
function cleanUser(u){return u&&{id:u.id,name:u.name,email:u.email,role:u.role,verified:u.verified}};
function overlap(a,b,c,d){return a<d&&c<b}
async function api(req,res,url){try{let d=await json(),u=await user(req);if(req.method==='GET'&&url==='/api/health')return send(res,200,{ok:true,service:'RentPy',version:'1.0.0'});
if(req.method==='POST'&&url==='/api/register'){let x=await body(req);if(!x.name||!x.email||!x.password||x.password.length<8)return send(res,400,{error:'Datos inválidos. La contraseña debe tener al menos 8 caracteres.'});let email=x.email.toLowerCase().trim();if(d.users.some(a=>a.email===email))return send(res,409,{error:'El email ya está registrado.'});let nu={id:id(),name:String(x.name).slice(0,80),email,password:hash(x.password),role:x.role==='host'?'host':'guest',verified:false,createdAt:new Date().toISOString()};d.users.push(nu);let token=crypto.randomBytes(32).toString('hex');d.sessions.push({token,userId:nu.id,expires:Date.now()+1000*60*60*24*7});await save(d);res.setHeader('Set-Cookie',`rp_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return send(res,201,{user:cleanUser(nu)});}
if(req.method==='POST'&&url==='/api/login'){let x=await body(req),nu=d.users.find(a=>a.email===String(x.email||'').toLowerCase().trim());if(!nu||nu.password!==hash(x.password||''))return send(res,401,{error:'Email o contraseña incorrectos.'});let token=crypto.randomBytes(32).toString('hex');d.sessions=d.sessions.filter(s=>s.userId!==nu.id);d.sessions.push({token,userId:nu.id,expires:Date.now()+1000*60*60*24*7});await save(d);res.setHeader('Set-Cookie',`rp_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return send(res,200,{user:cleanUser(nu)});}
if(req.method==='POST'&&url==='/api/logout'){d.sessions=d.sessions.filter(s=>s.token!==cookies(req).rp_session);await save(d);res.setHeader('Set-Cookie','rp_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{ok:true});}
if(req.method==='GET'&&url==='/api/me')return send(res,200,{user:cleanUser(u)});
if(req.method==='GET'&&url==='/api/listings'){let q=new URL(req.url,'http://x').searchParams,cat=q.get('cat'),city=q.get('city'),guests=Number(q.get('guests')||0);let out=d.listings.filter(l=>l.status==='active'&&(!cat||cat==='Todos'||l.category===cat)&&(!city||`${l.city} ${l.title}`.toLowerCase().includes(city.toLowerCase()))&&(!guests||l.guests>=guests));return send(res,200,{listings:out});}
if(req.method==='POST'&&url==='/api/listings'){if(!u||u.role!=='host')return send(res,403,{error:'Solo anfitriones pueden publicar.'});let x=await body(req);if(!x.title||!x.city||!Number(x.price)||!Number(x.guests))return send(res,400,{error:'Faltan datos obligatorios.'});let l={id:id(),hostId:u.id,title:String(x.title).slice(0,120),city:String(x.city).slice(0,80),category:x.category||'Casa',price:Number(x.price),guests:Number(x.guests),image:x.image||'',description:String(x.description||'').slice(0,2000),rating:0,status:'pending',createdAt:new Date().toISOString()};d.listings.push(l);await save(d);return send(res,201,{listing:l,message:'Anuncio enviado a revisión.'});}
if(req.method==='POST'&&url==='/api/bookings'){if(!u)return send(res,401,{error:'Iniciá sesión para reservar.'});let x=await body(req),l=d.listings.find(a=>a.id===x.listingId&&a.status==='active');if(!l)return send(res,404,{error:'Alojamiento no encontrado.'});let ci=new Date(x.checkin),co=new Date(x.checkout);if(!Number.isFinite(ci.getTime())||!Number.isFinite(co.getTime())||co<=ci)return send(res,400,{error:'Fechas inválidas.'});let conflict=d.bookings.some(b=>b.listingId===l.id&&['pending','confirmed'].includes(b.status)&&overlap(ci,co,new Date(b.checkin),new Date(b.checkout)));if(conflict)return send(res,409,{error:'Esas fechas ya no están disponibles.'});let nights=Math.ceil((co-ci)/86400000),total=nights*l.price;let b={id:id(),listingId:l.id,guestId:u.id,hostId:l.hostId,checkin:x.checkin,checkout:x.checkout,guests:Number(x.guests||1),nights,total,status:'pending_payment',createdAt:new Date().toISOString()};d.bookings.push(b);await save(d);return send(res,201,{booking:b,payment:{status:'not_connected',message:'Pago seguro pendiente de conectar con el adquirente contratado por RentPy.'}});}
if(req.method==='GET'&&url==='/api/bookings'){if(!u)return send(res,401,{error:'No autenticado'});let out=d.bookings.filter(b=>b.guestId===u.id||b.hostId===u.id);return send(res,200,{bookings:out.map(b=>({...b,listing:d.listings.find(l=>l.id===b.listingId)?.title}))});}
if(req.method==='POST'&&url==='/api/admin/login')return send(res,400,{error:'El acceso administrativo usa el mismo login y requiere role=admin.'});
if(req.method==='GET'&&url==='/api/admin/overview'){if(!u||u.role!=='admin')return send(res,403,{error:'No autorizado'});return send(res,200,{users:d.users.length,listings:d.listings.length,pending:d.listings.filter(l=>l.status==='pending').length,bookings:d.bookings.length});}
if(req.method==='POST'&&url.startsWith('/api/admin/listings/')){if(!u||u.role!=='admin')return send(res,403,{error:'No autorizado'});let lid=url.split('/').pop(),x=await body(req),l=d.listings.find(a=>a.id===lid);if(!l)return send(res,404,{error:'No encontrado'});if(!['active','rejected'].includes(x.status))return send(res,400,{error:'Estado inválido'});l.status=x.status;await save(d);return send(res,200,{listing:l});}
return send(res,404,{error:'Ruta no encontrada'});}catch(e){console.error(e);return send(res,500,{error:'Error interno'});}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*'});return res.end()}let url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url.pathname);let p=path.normalize(path.join(PUBLIC,url.pathname==='/'?'index.html':url.pathname));if(!p.startsWith(PUBLIC))return send(res,403,{error:'Forbidden'});try{let b=await fs.readFile(p),ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(b)}catch{send(res,404,{error:'Not found'})}});
server.listen(PORT,HOST,()=>console.log(`RentPy running at http://${HOST}:${PORT}`));
